defaults:
  - optrack/schema@_here_
  - _self_

input:
  file: schwab-transactions-dump.csv

output:
  max_table_width: 120
  output_date_format: %m/%d/%Y

db:
  url: mongodb://localhost:27017

action: list

hydra:
  job:
    chdir: false